---
- name: Generate XML configuration file with static client password
  hosts: localhost
  vars:
    # Retrieving the password from the environment variable
    client_password: "{{ lookup('env', 'XMLFILE_PASSWORD') }}"
    
  tasks:
    - name: Generate client setup XML
      template:
        src: install.xml.j2
        dest: /tmp/install.xml

    - name: Display generated XML file
      command: cat /tmp/install.xml
      register: xml_data

    - name: Show generated XML content
      debug:
        var: xml_data.stdout
        no_log: true  # Prevent displaying sensitive data like passwords
