---
- name: Generate XML configuration file with static client password
  hosts: localhost

  vars:
    client_password: "{{ lookup('env', 'CLIENT_PASSWORD') }}"

  tasks:
    - name: Generate client setup XML
      template:
        src: install.xml.j2
        dest: /tmp/install.xml

    - name: Display generated XML file
      command: cat /tmp/install.xml
      register: data

    - name: Show generated XML content
      debug:
        var: data.stdout
