---
- name: Generate XML configuration file with static client password
  hosts: localhost
  tasks:
    - name: Generate client setup XML
      template:
        src: install.xml.j2
        dest: /tmp/install.xml
      vars:
        client_password: "{{ ansible_password }}"  # Referencing AWX's stored password

    - name: Display generated XML file
      command: cat /tmp/install.xml
      register: data

    - name: Show generated XML content
      debug:
        var: data.stdout
